/*
 *GiANT - Graphical Algebra System
 *
 *Copyright (C) 2005  Aneesh Karve, e33nflow@users.sourceforge.net
 *
 *This program is free software; you can redistribute it and/or
 *modify it under the terms of the GNU General Public License
 *as published by the Free Software Foundation; either version 2
 *of the License, or (at your option) any later version.
 *
 *This program is distributed in the hope that it will be useful,
 *but WITHOUT ANY WARRANTY; without even the implied warranty of
 *MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *GNU General Public License for more details.
 *
 *You should have received a copy of the GNU General Public License
 *along with this program; if not, write to the Free Software
 *Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.*/

/*
 * VarTable.java
 *
 * Created on May 17, 2005, 6:33 PM
 */

package net.giantsystem.sf;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author  karve
 */
public class VarTable extends javax.swing.JTable {
    public final static String[] STD_COL_TITLES = {"Name", "Power Basis Representation "};
    public final static Class[] STD_COL_TYPES = {java.lang.Object.class, java.lang.Object.class};
    public final static int[] STD_COL_WIDS = {40, 280};
    //the first two columns are the same for all variable types; name + value
    public final static int NAME_COL = 0;
    public final static int VAL_COL = 1;
    private final DefaultTableModel model;
    private final Tab tab;//the tab this table lives in
	private final javax.swing.JTabbedPane tabbedPane;
    
    /** Creates new form BeanForm */
    public VarTable(final Tab t, final String[] names, final Class[] types, final int[] wids) {
        initComponents();
		//cross-platform; want to be sure unicode math chars are present
		setFont(new java.awt.Font("Lucida Grande", 0, 12));
        tab = t;
		tabbedPane = t.getInspector().getTabbedPane();
        
        setDefaultRenderer(BooleanPlus.class, new BooleanPlus.CellRenderer());
        model = new DefaultTableModel(null, names){
            Class[] typesCopy = types;
            
            public Class getColumnClass(int columnIndex) {
                return typesCopy [columnIndex];
            }
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        setModel(model);
        
        for(int i = 0; i < wids.length; i++){
            javax.swing.table.TableColumn column = getColumnModel().getColumn(i);
            column.setPreferredWidth(wids[i]);
        }
        

    }
    
    protected void addRow(Object[] rowData){
        model.addRow(rowData);
    }
    
    protected void insertRow(int i, Object[] rowData){
        model.insertRow(i, rowData);
    }
    
    public void valueChanged(javax.swing.event.ListSelectionEvent e){
        super.valueChanged(e);
        //System.err.println("VALUE");
        if(tab != null)// && !e.getValueIsAdjusting())//tab != null is to prevent constructor/startup woes            tab.updateSelectionDetail();
            tab.updateSelectionDetail();//getvalueadjusting messes up multiple select + show feature
    }
    
    public Variable getVariableAt(int r){
        if(r < 0 || r >= getRowCount())
            return null;
        else
            return (Variable) getValueAt(r, NAME_COL);
    }
    
    public String getNameAt(int r){
        if(r < 0 || r >= getRowCount())
            return null;
        else{
            Variable v = (Variable)getValueAt(r, NAME_COL);            return v.getName();
        }
    }
    
    private Class[] copyArray(Class[] c){
        Class[] copy = new Class[c.length];
        for(int i = 0; i < c.length; i++)
            copy[i] = c[i];
        return copy;
    }
	
	public Tab getTab(){
		return tab;
	}
    
    protected void handleMouseClicked(java.awt.event.MouseEvent evt) {
        return;
    }
    /*
	private void handleMouseMoved(java.awt.event.MouseEvent evt){
			//int tab = tabbedPane.indexAtLocation(evt.getX(), evt.getY());
			System.err.println(evt.getX() + "," +evt.getY());
			if(evt.getButton() != java.awt.event.MouseEvent.NOBUTTON){
				System.err.println("it's on");
				int tab = tabbedPane.indexAtLocation(evt.getX(), evt.getY());
				if(tab > 0)//no drops on elements panel allowed
					tabbedPane.setSelectedIndex(tab);
			}
	}*/
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        setDragEnabled(true);
        setGridColor(new java.awt.Color(153, 153, 153));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

    }
    // </editor-fold>//GEN-END:initComponents

	private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
		handleMouseClicked(evt);
	}//GEN-LAST:event_formMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
